server:
  port: 8080
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/buildwithtushar/Config-Repo
          default-label: main
          clone-on-start: true
          timeout: 10

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

